# This rule is not used by the project managed-namespace itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to operator.medinvention.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: managed-namespace
    app.kubernetes.io/managed-by: kustomize
  name: managednamespaceconfiguration-viewer-role
rules:
- apiGroups:
  - operator.medinvention.io
  resources:
  - managednamespaceconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.medinvention.io
  resources:
  - managednamespaceconfigurations/status
  verbs:
  - get
