apiVersion: operator.medinvention.io/v1alpha1
kind: ManagedNamespaceConfiguration
metadata:
  labels:
    app.kubernetes.io/name: managed-namespace
    app.kubernetes.io/managed-by: kustomize
  name: managednamespaceconfiguration-sample
spec:
  resources:
    - resource: 
        kind: RoleBinding
        apiVersion: rbac.authorization.k8s.io/v1
        name: admin-rolebiding
      content: |
        roleRef:
            kind: ClusterRole
            name: cluster-admin
            apiGroup: rbac.authorization.k8s.io
        subjects:
            - kind: Group
              name: project-group
